name: Deploy on push to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install target for WebAssembly
        run: rustup target add wasm32-wasip1
      - name: Build WebAssembly
        run: rustc main.rs --target wasm32-wasip1
      - name: Upload WebAssembly artifact to bucket
        run: |
          aws s3 cp --endpoint-url https://eyevinnlab-birme.minio-minio.auto.prod.osaas.io main.wasm s3://artifacts/main.wasm
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy as WASM runner
        run: |
          npx -y @osaas/cli remove ghdemo -y || true
          npx -y @osaas/cli create ghdemo -o WasmUrl=https://artifacts.osaas.io/artifacts/main.wasm
        env:
          OSC_ACCESS_TOKEN: ${{ secrets.OSC_ACCESS_TOKEN }}
 