name: Deploy on push to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install target for WebAssembly
        run: rustup target add wasm32-wasip1
      - name: Build WebAssembly
        run: rustc main.rs --target wasm32-wasip1
      - name: Publish WebAssembly artifact
        run: |
          gh release --latest -p create ./main.wasm
        env:
          GH_TOKEN: ${{ github.token }}
 